---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs

inputs:
- name: pcf-pipelines

params:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:

run:
  path: pcf-pipelines/tasks/gcp/check-opsman-dns/task.sh
