---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/rootfs

inputs:
- name: pcf-pipelines

run:
  path: pcf-pipelines/tasks/configure-tile/task.sh

params:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:
  OPSMAN_USERNAME:
  OPSMAN_PASSWORD:
  OPSMAN_CLIENT_ID:
  OPSMAN_CLIENT_SECRET:
  OPSMAN_IP:
  TILE_PROPERTIES:
  TILE_NETWORK:
  TILE_RESOURCES:
  TILE_PRODUCT_NAME:
