---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs

inputs:
- name: pcf-pipelines
- name: pivnet-opsmgr
- name: terraform-state

outputs:
- name: create-infrastructure-output

params:
  GCP_PROJECT_ID:
  GCP_REGION:
  GCP_SERVICE_ACCOUNT_KEY:
  GCP_ZONE_1:
  GCP_ZONE_2:
  GCP_ZONE_3:
  GCP_STORAGE_BUCKET_LOCATION:
  GCP_RESOURCE_PREFIX:
  PCF_ERT_DOMAIN:
  SYSTEM_DOMAIN:
  APPS_DOMAIN:

run:
  path: pcf-pipelines/tasks/gcp/create-infrastructure/task.sh
