---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/pks-kubectl

inputs:
- name: pcf-pipelines

run:
  path: pcf-pipelines/tasks/delete-all-pks-clusters/task.sh

params:
  PCF_PKS_API:
  PKS_CLI_USERNAME:
  PKS_CLI_PASSWORD:
  PKS_API_IP:
  PKS_API_DOMAIN:
  DEBUG:
