---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ttorii0609/gcloud-sdk-jq
    tag: beta

inputs:
- name: pcf-pipelines

run:
  path: pcf-pipelines/tasks/gcp/get-gcp-cost/task.sh

params:
  GCP_PROJECT_NAME:
  GCP_REGION:
  GCP_ZONE:
  GCP_SERVICE_KEY:
